version: '2.4'

networks:

  vpn_network:
    external:
      name: vpn

services:

  openvpn:
    image: stlouisn/openvpn
    container_name: openvpn
    hostname: openvpn
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/openvpn/config:/etc/openvpn
    cap_add:
      - NET_ADMIN
    networks:
      - vpn
    healthcheck:
      test: "ping -c 1 -W 3 -q google.com || (killall -s SIGUSR1 openvpn; exit 1)"
      start_period: 30s
      interval: 60s
      timeout: 30s
      retries: 5

# EXAMPLE CONTAINER BELOW

  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    environment:
      - LC_ALL=C.UTF-8
      - TZ=America/Halifax
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer/data:/data
    network_mode: service:openvpn
    depends_on:
      openvpn:
        condition: service_healthy
