version: '2.4'

networks:

  vpn_gateway:
    external:
    name: vpn_network

services:

  openvpn:
    image: stlouisn/openvpn:latest
    container_name: openvpn
    hostname: openvpn
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/openvpn/config:/etc/openvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    mem_limit: 500M
    memswap_limit: 500M
    logging:
      driver: json-file
        options:
          max-size: "10M"
          max-file: "3"
    healthcheck:
      test: "ping -c 1 -W 3 -q google.com || (killall -s SIGUSR1 openvpn; exit 1)"
      start_period: 30s
      interval: 60s
      timeout: 30s
      retries: 5
    networks:
      - vpn_gateway
    dns: 8.8.8.8

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    hostname: portainer
    environment:
      - LC_ALL=C.UTF-8
      - TZ=America/Halifax
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer/data:/data
    mem_limit: 50M
    memswap_limit: 50M
    logging:
      driver: json-file
        options:
          max-size: "10M"
          max-file: "3"
    #healthcheck:
    network_mode: service:openvpn
    depends_on:
      openvpn:
        condition: service_healthy
