version: '2.4'

networks:

  vpn_network:
    external:
      name: vlan30                     # <--- network must already exist

services:

  openvpn:
    image: stlouisn/openvpn
    container_name: openvpn
    hostname: openvpn
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
      - VPN_GATEWAY=123.123.123.123    # <--- vpn gateway
      - VPN_PORT=1234                  # <--- vpn port
      - VPN_PROTOCOL=udp               # <--- tcp/udp
      - LAN_GATEWAY=123.123.123.123    # <--- router IP
    restart: always
    volumes:
      - /docker/openvpn/config:/etc/openvpn:rw
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun      # <--- tun device must already exist
    networks:
      vpn_network:
        ipv4_address: 123.123.123.123  # <--- available IP on vlan30
    dns: 123.123.123.123               # <--- router IP or VPN DNS
    healthcheck:
      test: "ping -c 1 -W 3 -q google.com || (killall -s SIGUSR1 openvpn; exit 1)"
      start_period: 30s
      interval: 60s
      timeout: 30s
      retries: 5

  yourcontainer:
    image: yourcontainer/yourcontainer
    network_mode: service:openvpn
    depends_on:
      openvpn:
        condition: service_healthy
