#!/bin/bash

# ROLLING RELEASE
UBUNTU_VERSION=`curl -sS https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling` echo `curl -sS https://packages.ubuntu.com/${UBUNTU_VERSION}/amd64/openvpn/download | grep "Download Page" | awk -F "_" '{print $2}' | awk -F "ubuntu" '{print $1}'`
