version: 2.1

jobs:
  build-multiarch-container:
    resource_class: small
    docker:
      - image: cimg/base:stable
        auth:
          username: stlouisn
          password: $DOCKER_PASSWORD
    steps:
      - checkout:
          name: Checkout code
      - setup_remote_docker:
          name: Spin up remote Docker Engine
          version: 20.10.11
      - run:
          name: Setting environment variables
          command: |
            cat environment >> $BASH_ENV
            bash scripts/get_date.sh
            bash scripts/get_version.sh
            source $BASH_ENV
            env | grep '^BUILD_' | sort
            env | grep '^C_' | sort
            echo
      - run:
          name: Preparing dockerfile
          command: |
            bash scripts/set_labels.sh
            sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' dockerfile
            cat dockerfile
            echo
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_PASSWORD" ] && exit 1
            echo "$DOCKER_PASSWORD" | docker login --username=stlouisn --password-stdin
            echo
      - run:
          name: Configure Docker Buildx
          command: |
            docker buildx version
            echo
            sudo apt-get update -qq && sudo apt-get install -y binfmt-support qemu-user-static
            echo
            docker pull multiarch/qemu-user-static
            echo
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            echo
            docker context create buildcontext
            echo
            docker buildx create buildcontext --use --platform $BUILD_PLATFORMS > /dev/null
      - run:
          name: Build and push container
          no_output_timeout: 20m
          command: |
            docker buildx inspect --bootstrap
            echo
            docker buildx build --tag stlouisn/$C_NAME:$C_TAG --platform $BUILD_PLATFORMS --progress plain --push .
            echo

workflows:
  version: 2
  build-container:
    jobs:
      - build-multiarch-container
